<?php
require_once('controller/config.php');
require_once('controller/configdb.php');
require_once('controller/loginController.php');
// ganti judul dan keterangan login disini //
$judul_login = "Selamat datang kembali!";
$ket_login = "Silahkan <code>Log-in</code> untuk melanjutkan!";
// end ganti judul dan keterangan login disini //
$namaSekolah = getConfig('settingheader');
$logoSekolah = "img/".getConfig('logoHeader');
$alamat = getConfig('namaJalan');
$error = false;
$title = "Halaman Login";
if (isset($_SESSION['login']) && isset($_SESSION['user_id']) > 0 ) {
  if (getTokenLogin($_SESSION['user_id']) == $_SESSION['user_name'].$_SESSION['user_ip']) {
    header('Location:index.php');
    exit();
  }
}
$dt = date('Y');
$flylogin = "";
$flylogin .= "";
$flylogin .= '<!DOCTYPE html>';
$flylogin .= '<html lang="id">';
$flylogin .= '<head>';
$flylogin .= '<base href="./">';
$flylogin .= '<meta charset="utf-8">';
$flylogin .= '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
$flylogin .= '<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">';
$flylogin .= '<meta name="description" content="eIS-F (FlyExam Server) Aplikasi ujian online berbasis WEB dan Mobile Android">';
$flylogin .= '<meta name="keyword" content="FlyExam, FlyExam Browser, FLY, CBT">';
$flylogin .= '<meta name="author" content="Harison">';
$flylogin .= '<title> '.$title.' ─  '.$namaSekolah.'</title>';
$flylogin .= '<link rel="icon" type="image/ico" href="./img/flyexam.ico" sizes="any" />';
$flylogin .= '<link href="vendors/@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">';
$flylogin .= '<link href="vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">';
$flylogin .= '<link href="vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">';
$flylogin .= '<link href="vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">';
$flylogin .= '<link href="css/style.css" rel="stylesheet">';
$flylogin .= '<link href="vendors/pace-progress/css/pace.min.css" rel="stylesheet">';
$flylogin .= '<link href="css/toastr.min.css" rel="stylesheet"/>';
$flylogin .= '</head>';
$flylogin .= '<div class="loader"></div>';
$flylogin .= '<body class="app flex-row align-items-center">';
$flylogin .= '<div class="container">';
$flylogin .= '<div class="row justify-content-center">';
$flylogin .= '<div class="col-md-8">';
$flylogin .= '<div class="card-group">';
$flylogin .= '<div class="card p-4">';
$flylogin .= '<form id="frmLogin" action="" method="post">';
$flylogin .= '<div class="card-body">';
$flylogin .= '<h4 id="logo" style="color:#333"><strong>'.$judul_login.'</strong></h4>';
$flylogin .= '<p style="line-height:18px" class="mb-3 text-muted">'.$ket_login.'</p>';
if ($error) {
  $flylogin .= '<p class="mb-0">';
  $flylogin .= '<div id="error" class="mb-0 alert-sm alert alert-danger alert-dismissible fade show" role="alert">';
  $flylogin .= '<strong>Ouppsss!! </strong> Username atau Password yang Anda masukkan salah.';
  $flylogin .= '<button type="button" class="close" data-dismiss="alert" aria-label="Close">';
  $flylogin .= '<span aria-hidden="true">&times;</span>';
  $flylogin .= '</button>';
  $flylogin .= '</div>';
  $flylogin .= '</p>';
}
$flylogin .= '<div class="input-group mb-1">';
$flylogin .= '<div class="input-group-prepend">';
$flylogin .= '<span class="input-group-text">';
$flylogin .= '<i class="icon-user"></i>';
$flylogin .= '</span>';
$flylogin .= '</div>';
$flylogin .= '<input autocomplete="off" id="uname" name="uname" class="form-control" type="text" placeholder="Username">';
$flylogin .= '</div>';
$flylogin .= '<div class="input-group mb-4">';
$flylogin .= '<div class="input-group-prepend">';
$flylogin .= '<span class="input-group-text">';
$flylogin .= '<i class="icon-lock"></i>';
$flylogin .= '</span>';
$flylogin .= '</div>';
$flylogin .= '<input id="pwd" name="pwd" class="form-control" type="password" placeholder="Password">';
$flylogin .= '</div>';
$flylogin .= '<div class="row mt-0">';
$flylogin .= '<div class="col-md-12 mb-2" style="margin-top:-14px">';
$flylogin .= '<div class="form-check checkbox">';
$flylogin .= '<label class="form-check-label text-muted" for="x_show">';
$flylogin .= '<input class="form-check-input" name="x_show" id="x_show" type="checkbox" value="1"/>';
$flylogin .= 'Tampilkan Password</label>';
$flylogin .= '</div>';
$flylogin .= '<div class="form-check checkbox">';
$flylogin .= '<label class="form-check-label text-muted" for="x_rmbr">';
$flylogin .= '<input class="form-check-input" name="x_rmbr" id="x_rmbr" type="checkbox" value="1"/>';
$flylogin .= 'Selalu ingat saya</label>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '<div class="col-7">';
$flylogin .= '<button id="login" name="login" class="btn btn-block btn-pill btn-sm btn-outline-2x btn-primary px-4" type="button" title="Log-in untuk melanjutkan"> <b>Log-in</b> <i class="float-right mt-1 icon icon-login"></i></button>';
$flylogin .= '</div>';
$flylogin .= '<div class="col-5 text-right">';
$flylogin .= '<button id="forgotpwd" class="btn btn-link px-0 mb-0" type="button"><small>Lupa password?</small></button>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '</form>';
$flylogin .= '</div>';
$flylogin .= '<div style="background-image:url(img/bg-profile-new.png);background-repeat: no-repeat;background-size: cover;background-position: center;background-color: #cccccc;" class="card text-white py-5 d-md-down-none" style="width:44%">';
$flylogin .= '<div class="card-body text-center">';
$flylogin .= '<div>';
$flylogin .= '<img class="mb-2" src="'.$logoSekolah.'" width="80px" height="70px;" alt="'.$namaSekolah.'">';
$flylogin .= '<h5 class="mt-0"><strong>'.$namaSekolah.'</strong></h5>';
$flylogin .= '<p style="line-height:18px">'.$alamat.'</p>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '</div>';
$flylogin .= '<div class="col-md-12 mt-3 text-center"><small>';
$flylogin .= '<a class="text-muted" id="cp" href="index.php">EiS (Educational Information System)</a>';
$flylogin .= '<span id="delta"> &copy; '.$dt.' Delta Microtech.  All rights reserved.</span>';
$flylogin .= '</small></div>';
$flylogin .= '</div>';
$flylogin .= '<script src="vendors/jquery/js/jquery.min.js"></script>';
$flylogin .= '<script src="vendors/bootstrap/js/bootstrap.min.js"></script>';
$flylogin .= '<script type="text/javascript" src="js/toastr.min.js"></script>';
$flylogin .= '<script type="text/javascript" src="js/load.js"></script>';
$flylogin .= '<script type="text/javascript" src="js/login.js"></script>';
$flylogin .= '<script type="text/javascript" src="js/select2.full.min.js"></script>';
$flylogin .= '</body>';
$flylogin .= '</html>';
print($flylogin);
